// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloBD;

namespace ModeloBD.Migrations
{
    [DbContext(typeof(Repositorio))]
    [Migration("20220204172552_SisEval4.2.2")]
    partial class SisEval422
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelo.Entidades.Aumento", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("BonoId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId", "BonoId");

                    b.HasIndex("BonoId");

                    b.ToTable("Aumentos");
                });

            modelBuilder.Entity("Modelo.Entidades.Bono", b =>
                {
                    b.Property<int>("BonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("BonoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Bonos");
                });

            modelBuilder.Entity("Modelo.Entidades.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salario")
                        .HasColumnType("real");

                    b.Property<int>("SueldoId")
                        .HasColumnType("int");

                    b.HasKey("CargoId");

                    b.HasIndex("SueldoId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Modelo.Entidades.Control_Asistencia", b =>
                {
                    b.Property<int>("Control_AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EntradaAlmuerzo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SalidaAlmuerzo")
                        .HasColumnType("datetime2");

                    b.HasKey("Control_AsistenciaId");

                    b.ToTable("Control_Asistencias");
                });

            modelBuilder.Entity("Modelo.Entidades.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Modelo.Entidades.DesempenoEm", b =>
                {
                    b.Property<int>("DesempenoEmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesempenoEmId");

                    b.ToTable("desempenoEm");
                });

            modelBuilder.Entity("Modelo.Entidades.DesempenoSc", b =>
                {
                    b.Property<int>("DesempenoScId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesempenoScId");

                    b.ToTable("DesempenoSc");
                });

            modelBuilder.Entity("Modelo.Entidades.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int>("Control_AsistenciaId")
                        .HasColumnType("int");

                    b.Property<int>("DepartamendoId")
                        .HasColumnType("int");

                    b.Property<int>("DesempenoEmId")
                        .HasColumnType("int");

                    b.Property<int>("DesempenoScId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("SueldoId")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("Control_AsistenciaId");

                    b.HasIndex("DepartamendoId");

                    b.HasIndex("DesempenoEmId");

                    b.HasIndex("DesempenoScId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("SueldoId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Modelo.Entidades.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<float>("Importe")
                        .HasColumnType("real");

                    b.Property<int>("SueldoId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("SueldoId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Modelo.Entidades.Horario_Det", b =>
                {
                    b.Property<int>("Horario_DetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("Horario_DetId");

                    b.HasIndex("PermisoId")
                        .IsUnique();

                    b.ToTable("Horario_Dets");
                });

            modelBuilder.Entity("Modelo.Entidades.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Control_AsistenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Horario_DetId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermisoId");

                    b.HasIndex("Control_AsistenciaId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Modelo.Entidades.Sucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SucursalId");

                    b.ToTable("Sucursals");
                });

            modelBuilder.Entity("Modelo.Entidades.Sueldo", b =>
                {
                    b.Property<int>("SueldoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FacturasId")
                        .HasColumnType("int");

                    b.Property<float>("SueldoBase")
                        .HasColumnType("real");

                    b.HasKey("SueldoId");

                    b.ToTable("Sueldos");
                });

            modelBuilder.Entity("Modelo.Entidades.Aumento", b =>
                {
                    b.HasOne("Modelo.Entidades.Bono", "Bono")
                        .WithMany("Aumentos")
                        .HasForeignKey("BonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Entidades.Empleado", "Empleado")
                        .WithMany("Aumentos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bono");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Modelo.Entidades.Bono", b =>
                {
                    b.HasOne("Modelo.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Modelo.Entidades.Cargo", b =>
                {
                    b.HasOne("Modelo.Entidades.Sueldo", "Sueldo")
                        .WithMany("Cargos")
                        .HasForeignKey("SueldoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sueldo");
                });

            modelBuilder.Entity("Modelo.Entidades.Empleado", b =>
                {
                    b.HasOne("Modelo.Entidades.Control_Asistencia", "Control_Asistencia")
                        .WithMany("Empleados")
                        .HasForeignKey("Control_AsistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Entidades.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamendoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Entidades.DesempenoEm", "DesempenoEm")
                        .WithMany("Empleados")
                        .HasForeignKey("DesempenoEmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Entidades.DesempenoSc", "DesempenoSc")
                        .WithMany("Empleados")
                        .HasForeignKey("DesempenoScId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Entidades.Sucursal", "Sucursal")
                        .WithMany("Empleados")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Entidades.Sueldo", "Sueldo")
                        .WithMany("Empleados")
                        .HasForeignKey("SueldoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control_Asistencia");

                    b.Navigation("Departamento");

                    b.Navigation("DesempenoEm");

                    b.Navigation("DesempenoSc");

                    b.Navigation("Sucursal");

                    b.Navigation("Sueldo");
                });

            modelBuilder.Entity("Modelo.Entidades.Factura", b =>
                {
                    b.HasOne("Modelo.Entidades.Sueldo", "Sueldo")
                        .WithMany("Facturas")
                        .HasForeignKey("SueldoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sueldo");
                });

            modelBuilder.Entity("Modelo.Entidades.Horario_Det", b =>
                {
                    b.HasOne("Modelo.Entidades.Permiso", "Permiso")
                        .WithOne("Horario_Det")
                        .HasForeignKey("Modelo.Entidades.Horario_Det", "PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("Modelo.Entidades.Permiso", b =>
                {
                    b.HasOne("Modelo.Entidades.Control_Asistencia", "Control_Asistencia")
                        .WithMany("Permisos")
                        .HasForeignKey("Control_AsistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control_Asistencia");
                });

            modelBuilder.Entity("Modelo.Entidades.Bono", b =>
                {
                    b.Navigation("Aumentos");
                });

            modelBuilder.Entity("Modelo.Entidades.Control_Asistencia", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("Modelo.Entidades.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Modelo.Entidades.DesempenoEm", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Modelo.Entidades.DesempenoSc", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Modelo.Entidades.Empleado", b =>
                {
                    b.Navigation("Aumentos");
                });

            modelBuilder.Entity("Modelo.Entidades.Permiso", b =>
                {
                    b.Navigation("Horario_Det");
                });

            modelBuilder.Entity("Modelo.Entidades.Sucursal", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Modelo.Entidades.Sueldo", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Empleados");

                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
